---

- name: replace line
  lineinfile: 
    path: /etc/apache2/ports.conf
    regexp: '^(.*)Listen 80(.*)$' 
    line: 'Listen 8080'
    firstmatch: yes
    state: present


- name: Insert Servername
  lineinfile:
    path: /etc/apache2/apache2.conf
    insertafter: '^# vim: syntax=apache ts=4 sw=4 sts=4 sr noet'
    line: 'Servername 127.0.0.1'
    firstmatch: yes
    state: present
