---
- name: Install mysql
  apt:
    name: ['mysql-server', 'mysql-client', 'python3-mysqldb']
    state: present
    update_cache: yes

  # Allows python to create and manipulate mysql config
- name: Ensure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Create system-wide mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Create mysql configuration file for `{{ mysql_superuser }}`
  template:
    src: sup_my.cnf.j2
    dest: "{{ mysql_superuser_home }}/.my.cnf"
    #notify:
    #- Restart Mysql


- name: Update mysql password for superuser `{{ mysql_superuser }}`
  mysql_user:
    # Update the superuser to have all grants and a password
    name: "{{ mysql_superuser }}"
    host: localhost
    password: "{{ mysql_superuser_password }}"
    priv: "*.*:ALL,GRANT"
    # Login *as root* to perform this change, even though you might
    # be altering the root user itself
    login_user: root
    login_password: ""
    login_port: "{{ mysql_port }}"
    login_host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    # As a good measure,have ansible check whether an implicit login
    # is possible first
    check_implicit_admin: yes
    #notify:
    #- Restart mysql   

